### ISSUE TITLE
Avoid starting xvfb in master if xdist is on

### ISSUE THREAD

**Issue by ionelmc** [The-Compiler/pytest-xvfb#14]
Xvfb would only be needed in slaves anyway.

**Comment by The-Compiler** [comment]
Makes sense I think, but I don't use xdist myself :wink:

**Comment by kierun** [comment]
I think I have a similar problem. When running `py.test -n 4` things work just fine. However, `py.test -n 5` causes one of the workers to die. It seems that `pytest-xdist` copes with this just fine, but you do get an ugly trace stack:

```
============================= test session starts ==============================platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0           
rootdir: /home/whatever/repos/raiju, inifile: setup.cfg                             
plugins: xvfb-1.0.0, xdist-1.19.0, forked-0.2, colordots-0.1, asyncio-0.6.0     
gw0 ok / gw1 C / gw2 C / gw3 C / gw4 CINTERNALERROR> Traceback (most recent call last):                                                                         
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/main.py", line 106, in wrap_session                                    
INTERNALERROR>     config._do_configure()                                       
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/config.py", line 935, in _do_configure                                 
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))                                                                           
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 750, in call_historic               
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)                                                                             
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec                   
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)           
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>                    
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()        
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute                     
INTERNALERROR>     res = hook_impl.function(*args)                              
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/pytest_xvfb.py", line 87, in pytest_configure                                  
INTERNALERROR>     config.xvfb.start()                                          
INTERNALERROR>   File "/home/whatever/.virtualenvs/raiju/lib/python3.6/site-packages/pytest_xvfb.py", line 52, in start                                             
INTERNALERROR>     raise XvfbExitedError("Xvfb exited with exit code {0}".format(ret))                                                                          
INTERNALERROR> pytest_xvfb.XvfbExitedError: Xvfb exited with exit code 1
pytest_xvfb.XvfbExitedError: Xvfb exited with exit code 1        
[gw2] node down: Not properly terminated                                        
Replacing crashed slave gw2                                                     
gw0 [134] / gw1 [134] / gw5 [134] / gw3 [134] / gw4 [134]                       
scheduling tests via LoadScheduling                                             
...............................................................................Xlib:  extension "RANDR" missing on display ":1009".                             
........................Xlib:  extension "RANDR" missing on display ":1017".    
.....................Xlib:  extension "RANDR" missing on display ":1005".       
....Xlib:  extension "RANDR" missing on display ":1021".                        
......                                                                          
---------- generated xml file: /home/whatever/unit_tests.xml -----------
========================== 134 passed in 3.56 seconds ==========================
```

**Comment by The-Compiler** [comment]
Fixed via #18

**Comment by KjellMorgenstern** [comment]
We are importing pyautogui.py in our test_Foo.py .
pyautogui checks for a display. To be exact, it checks for os.environ['DISPLAY'] . This will then cause

```
test_whatever.py:12: in <module>
    import pyautogui
/usr/local/lib/python3.11/dist-packages/pyautogui/__init__.py:246: in <module>
    import mouseinfo
/usr/local/lib/python3.11/dist-packages/mouseinfo/__init__.py:223: in <module>
    _display = Display(os.environ['DISPLAY'])
<frozen os>:679: in __getitem__
    ???
E   KeyError: 'DISPLAY'

```

I am not sure if setting PYTEST_XDIST_WORKER on the xdist master, to disable the check, is a good idea.
To fix this I am commenting out the is_xdist_master(config) check in the pytest_configure method, but of course this patch needs to be done all the time when installing or updating xdist-xvfb.

Would it make sense to add an option to override this check?

**Comment by The-Compiler** [comment]
Fine by me, though I don't really have an opinion on this as I never used this kind of configuration myself. @ionelmc @touilleMan any thoughts on this?
