### ISSUE TITLE
Race condition or something when using xdist

### ISSUE THREAD

**Issue by ionelmc** [The-Compiler/pytest-xvfb#16]
I have this problem:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python2.7
cachedir: .cache
metadata: {'Python': '2.7.12', 'Platform': 'Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial', 'Packages': {'py': '1.5.2', 'pytest': '3.3.1', 'pluggy': '0.6.0'}, 'Plugins': {'raisesregexp': '2.1', 'profiling': '1.2.11', 'cov': '2.5.1', 'tornado': '0.4.5', 'pythonpath': '0.7.1', 'splinter': '1.8.5', 'benchmark': '3.1.1', 'xdist': '1.21.0', 'django': '3.1.2', 'fixture-tools': '1.0.0', 'remove-stale-bytecode': '3.0', 'xvfb': '1.0.0', 'html': '1.16.0', 'aspectlib': '1.4.2', 'runfailed': '0.6', 'forked': '0.2', 'instafail': '0.3.0', 'colordots': '1.1', 'stepwise': '0.4', 'metadata': '1.5.1'}}
Django settings: aaeweb.settings_testing (from environment variable)
benchmark: 3.1.1 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /app, inifile: pytest.ini
plugins: xvfb-1.0.0, xdist-1.21.0, tornado-0.4.5, stepwise-0.4, splinter-1.8.5, runfailed-0.6, remove-stale-bytecode-3.0, raisesregexp-2.1, pythonpath-0.7.1, profiling-1.2.11, metadata-1.5.1, instafail-0.3.0, html-1.16.0, forked-0.2, fixture-tools-1.0.0, django-3.1.2, cov-2.5.1, colordots-1.1, benchmark-3.1.1, aspectlib-1.4.2
gw0 I / gw1 I

[gw0] linux2 Python 2.7.12 cwd: /app

[gw1] linux2 Python 2.7.12 cwd: /app
[2017-12-27 16:26:48,815 pid=74   ] DEBUG    | easyprocess               | param: "['Xvfb', '-help']" 
[2017-12-27 16:26:48,816 pid=74   ] DEBUG    | easyprocess               | command: ['Xvfb', '-help']
[2017-12-27 16:26:48,816 pid=74   ] DEBUG    | easyprocess               | joined command: Xvfb -help
[2017-12-27 16:26:48,824 pid=74   ] DEBUG    | easyprocess               | process was started (pid=160)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | process has ended
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | return code=0
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | stdout=
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | stderr=use: X [:<display>] [option]
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -a #                   default pointer acceleration (factor)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -ac                    disable access control restrictions
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -audit int             set audit trail level
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -auth file             select authorization file
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -br                    create root window with black background
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > +bs                    enable any backing store support
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -bs                    disable any backing store support
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -c                     turns off key-click
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > c #                    key-click volume (0-100)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -cc int                default color visual class
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -nocursor              disable the cursor
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -core                  generate core dump on fatal error
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -displayfd fd          file descriptor to write display number to when ready to connect
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -dpi int               screen resolution in dots per inch
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -dpms                  disables VESA DPMS monitor control
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -deferglyphs [none|all|16] defer loading of [no|all|16-bit] glyphs
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -f #                   bell base (0-100)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -fc string             cursor font
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -fn string             default font name
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -fp string             default font path
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -help                  prints message with these options
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > +iglx                  Allow creating indirect GLX contexts
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -iglx                  Prohibit creating indirect GLX contexts (default)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -I                     ignore all remaining arguments
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -ld int                limit data space to N Kb
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -lf int                limit number of open files to N
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -ls int                limit stack space to N Kb
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -nolock                disable the locking mechanism
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -maxclients n          set maximum number of clients (power of two)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -nolisten string       don't listen on protocol
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -listen string         listen on protocol
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -noreset               don't reset after last client exists
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -background [none]     create root window with no background
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -reset                 reset after last client exists
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -p #                   screen-saver pattern duration (minutes)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -pn                    accept failure to listen on all ports
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -nopn                  reject failure to listen on all ports
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -r                     turns off auto-repeat
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > r                      turns on auto-repeat 
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -render [default|mono|gray|color] set render color alloc policy
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -retro                 start with classic stipple and cursor
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -s #                   screen-saver timeout (minutes)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -seat string           seat to run on
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -t #                   default pointer threshold (pixels/t)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -terminate             terminate at server reset
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -to #                  connection time out
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -tst                   disable testing extensions
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > ttyxx                  server started from init on /dev/ttyxx
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > v                      video blanking for screen-saver
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -v                     screen-saver without video blanking
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -wm                    WhenMapped default backing-store
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -wr                    create root window with white background
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -maxbigreqsize         set maximal bigrequest size 
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > +xinerama              Enable XINERAMA extension
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -xinerama              Disable XINERAMA extension
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -dumbSched             Disable smart scheduling, enable old behavior
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -schedInterval int     Set scheduler interval in msec
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -sigstop               Enable SIGSTOP based startup
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > +extension name        Enable extension
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -extension name        Disable extension
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -query host-name       contact named host for XDMCP
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -broadcast             broadcast for XDMCP
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -multicast [addr [hops]] IPv6 multicast for XDMCP
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -indirect host-name    contact named host for indirect XDMCP
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -port port-num         UDP port number to send messages to
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -from local-address    specify the local address to connect from
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -once                  Terminate server after one session
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -class display-class   specify display class to send in manage
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -cookie xdm-auth-bits  specify the magic cookie for XDMCP
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -displayID display-id  manufacturer display ID for request
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > [+-]accessx [ timeout [ timeout_mask [ feedback [ options_mask] ] ] ]
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | >                        enable/disable accessx key sequences
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -ardelay               set XKB autorepeat delay
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -arinterval            set XKB autorepeat interval
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -screen scrn WxHxD     set screen's width, height, depth
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -pixdepths list-of-int support given pixmap depths
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > +/-render		   turn on/off RENDER extension support(default on)
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -linebias n            adjust thin line pixelization
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -blackpixel n          pixel value for black
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -whitepixel n          pixel value for white
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -fbdir directory       put framebuffers in mmap'ed files in directory
[2017-12-27 16:26:48,827 pid=74   ] DEBUG    | easyprocess               | > -shmem                 put framebuffers in shared memory
[2017-12-27 16:26:48,828 pid=74   ] DEBUG    | easyprocess               | param: "['xauth', '-h']" 
[2017-12-27 16:26:48,829 pid=74   ] DEBUG    | easyprocess               | command: ['xauth', '-h']
[2017-12-27 16:26:48,829 pid=74   ] DEBUG    | easyprocess               | joined command: xauth -h
[2017-12-27 16:26:48,835 pid=74   ] DEBUG    | easyprocess               | process was started (pid=162)
[2017-12-27 16:26:48,835 pid=74   ] DEBUG    | easyprocess               | process has ended
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | return code=1
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | stdout=
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | stderr=usage:  xauth [-options ...] [command arg ...]
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > where options include:
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -f authfilename                name of authority file to use
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -v                             turn on extra messages
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -q                             turn off extra messages
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -i                             ignore locks on authority file
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -b                             break locks on authority file
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     -V                             show version number of xauth
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > and commands have the following syntax:
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     add dpyname protoname hexkey   add entry
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     exit                           save changes and exit program
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     extract filename dpyname...    extract entries into file
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     help [topic]                   print help
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     info                           print information about entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     list [dpyname...]              list entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     merge filename...              merge entries from files
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     nextract filename dpyname...   numerically extract entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     nlist [dpyname...]             numerically list entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     nmerge filename...             numerically merge entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     quit                           abort changes and exit program
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     remove dpyname...              remove entries
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     source filename                read commands from file
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     version                        show version number of xauth
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     ?                              list available commands
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     generate dpyname protoname [options]  use server to generate entry
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >     options are:
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >       timeout n    authorization expiration time in seconds
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >       trusted      clients using this entry are trusted
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >       untrusted    clients using this entry are untrusted
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >       group n      clients using this entry belong to application group n
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | >       data hexkey  auth protocol specific data needed to generate the entry
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > A dash may be used with the "merge" and "source" to read from the
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | > standard input.  Commands beginning with "n" use numeric format.
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | param: "['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x16', ':1004']" 
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x16', ':1004']
[2017-12-27 16:26:48,836 pid=74   ] DEBUG    | easyprocess               | joined command: Xvfb -br -nolisten tcp -screen 0 800x600x16 :1004
[2017-12-27 16:26:48,837 pid=74   ] DEBUG    | easyprocess               | param: "['xauth', '-h']" 
[2017-12-27 16:26:48,837 pid=74   ] DEBUG    | easyprocess               | command: ['xauth', '-h']
[2017-12-27 16:26:48,837 pid=74   ] DEBUG    | easyprocess               | joined command: xauth -h
[2017-12-27 16:26:48,843 pid=74   ] DEBUG    | easyprocess               | process was started (pid=164)
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | process has ended
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | return code=1
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | stdout=
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | stderr=usage:  xauth [-options ...] [command arg ...]
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > where options include:
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -f authfilename                name of authority file to use
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -v                             turn on extra messages
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -q                             turn off extra messages
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -i                             ignore locks on authority file
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -b                             break locks on authority file
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     -V                             show version number of xauth
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > and commands have the following syntax:
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     add dpyname protoname hexkey   add entry
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     exit                           save changes and exit program
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     extract filename dpyname...    extract entries into file
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     help [topic]                   print help
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     info                           print information about entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     list [dpyname...]              list entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     merge filename...              merge entries from files
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     nextract filename dpyname...   numerically extract entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     nlist [dpyname...]             numerically list entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     nmerge filename...             numerically merge entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     quit                           abort changes and exit program
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     remove dpyname...              remove entries
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     source filename                read commands from file
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     version                        show version number of xauth
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     ?                              list available commands
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     generate dpyname protoname [options]  use server to generate entry
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >     options are:
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >       timeout n    authorization expiration time in seconds
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >       trusted      clients using this entry are trusted
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >       untrusted    clients using this entry are untrusted
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >       group n      clients using this entry belong to application group n
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | >       data hexkey  auth protocol specific data needed to generate the entry
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > 
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > A dash may be used with the "merge" and "source" to read from the
[2017-12-27 16:26:48,844 pid=74   ] DEBUG    | easyprocess               | > standard input.  Commands beginning with "n" use numeric format.
[2017-12-27 16:26:48,845 pid=74   ] DEBUG    | easyprocess               | param: "['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x16', ':1005']" 
[2017-12-27 16:26:48,845 pid=74   ] DEBUG    | easyprocess               | command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x16', ':1005']
[2017-12-27 16:26:48,845 pid=74   ] DEBUG    | easyprocess               | joined command: Xvfb -br -nolisten tcp -screen 0 800x600x16 :1005
[2017-12-27 16:26:48,851 pid=74   ] DEBUG    | easyprocess               | process was started (pid=166)
[2017-12-27 16:26:48,851 pid=74   ] DEBUG    | pyvirtualdisplay.abstractdisplay | DISPLAY=:1005
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | process has ended
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | return code=1
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | stdout=
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | stderr=(EE) 
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | > Fatal server error:
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | > (EE) Server is already active for display 1005
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | > 	If this server is no longer running, remove /tmp/.X1005-lock
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | > 	and start again.
[2017-12-27 16:26:48,952 pid=74   ] DEBUG    | easyprocess               | > (EE) 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 99, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 921, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 628, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pytest_xvfb.py", line 93, in pytest_configure
INTERNALERROR>     config.xvfb.start()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pytest_xvfb.py", line 58, in start
INTERNALERROR>     '\n    '.join(stderr.splitlines())))
INTERNALERROR> XvfbExitedError: Xvfb exited with exit code 1
INTERNALERROR> Xvfb stdout:
INTERNALERROR>     
INTERNALERROR> Xvfb stderr:
INTERNALERROR>     (EE) 
INTERNALERROR>     Fatal server error:
INTERNALERROR>     (EE) Server is already active for display 1005
INTERNALERROR>     	If this server is no longer running, remove /tmp/.X1005-lock
INTERNALERROR>     	and start again.
INTERNALERROR>     (EE)
```

Sometimes wonder if switching to pyvirtualdisplay was a good idea ...

**Comment by The-Compiler** [comment]
Shouldn't this be fixed when #14 is?

**Comment by ionelmc** [comment]
Well actually I looked more into it and this is the real problem: https://github.com/ponty/PyVirtualDisplay/issues/30

**Comment by ionelmc** [comment]
Anyway, meanwhile I'm gonna do this ugly as hell workaround in my conftest:


```python
from pyvirtualdisplay import abstractdisplay
abstractdisplay.RANDOMIZE_DISPLAY_NR = True
abstractdisplay.random = random
random.seed()
```
