### ISSUE TITLE
Incompatibility with Pytest 4.1

### ISSUE THREAD

**Issue by henriquegemignani** [The-Compiler/pytest-xvfb#17]
``` 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "Python37\lib\site-packages\_pytest\main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "Python37\lib\site-packages\_pytest\main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "Python37\lib\site-packages\_pytest\main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "Python37\lib\site-packages\_pytest\main.py", line 468, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "Python37\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "Python37\lib\site-packages\pytest_xvfb.py", line 104, in pytest_collection_modifyitems
INTERNALERROR>     if item.get_marker('no_xvfb') and item.config.xvfb is not None:
INTERNALERROR> AttributeError: 'Function' object has no attribute 'get_marker'
```

See https://github.com/pytest-dev/pytest/pull/4564.

**Comment by The-Compiler** [comment]
I fixed this in c65ce4e387bd5e92dda0b08d4f61f652a6867bed (already before this issue, but forgot to push it before going to bed :wink:) and released v1.2.0!
