### ISSUE TITLE
Running tests on (non-headless) macOS system results in internal error

### ISSUE THREAD

**Issue by j9ac9k** [The-Compiler/pytest-xvfb#19]
When running `pytest tests/`  with `pytest-xvfb` installed on my macOS system I get the following in my terminal:

```
/usr/local/bin/pipenv run pytest tests/
Loading .env environment variables…
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/_pytest/main.py", line 205, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 663, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pytest_xvfb.py", line 93, in pytest_configure
INTERNALERROR>     config.xvfb.start()
INTERNALERROR>   File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/pytest_xvfb.py", line 58, in start
INTERNALERROR>     '\n    '.join(stderr.splitlines())))
INTERNALERROR> pytest_xvfb.XvfbExitedError: Xvfb exited with exit code 1
INTERNALERROR> Xvfb stdout:
INTERNALERROR>
INTERNALERROR> Xvfb stderr:
INTERNALERROR>     _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
INTERNALERROR>     _XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
INTERNALERROR>     _XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
INTERNALERROR>     (EE)
INTERNALERROR>     Fatal server error:
INTERNALERROR>     (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
make: *** [test] Error 3
```

Removing `pytest-xvfb` results in everything going fine.  I was hoping to be able to keep the commands to run the test code locally and on the CI system the same.

**Comment by j9ac9k** [comment]
re-reading the docs, as I have xvfb installed on my machine (looks like it was bundled with `brew cask xquartz`) which is likely why `pytest-xvfb` is trying to call it.  Any suggestions for how to address this?

**Comment by The-Compiler** [comment]
I assume if you run `Xvfb` by hand, you get the same output? I don't think there's much the plugin can do here - either don't have `Xvfb` in your path if it doesn't work, or disable the plugin via `-p no:xvfb`, or don't install it at all.

**Comment by j9ac9k** [comment]
that's fair; most likely I'll just create a `make test` and `make test-ci` makefile rule in my case.  Thank for your time, and thanks for this plugin.
